name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build library 
      run: cd libgb-rs/ && cargo build --verbose
    - name: Run tests for library
      run: cd libgb-rs/ && cargo test --verbose
    - name: Build executable
      run: cd gb-rs/ && cargo build --verbose
    - name: Test executable
      run: cd gb-rs/ && cargo test --verbose
