name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: cd libgb-rs/
    - name: Build library 
      run: cargo build --verbose
    - name: Run tests for library
      run: cargo test --verbose
    - run: cd ../gb-rs/
    - name: Build executable
      run: cargo build --verbose
    - name: Test executable
      run: cargo test --verbose
